name: Hello world

on:
    workflow_dispatch:

jobs:
    say-hello-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello World!"

    say-hello-python:
        runs-on: ubuntu-24.04
        steps:
            - run: print("Hello World")
              shell: python